### ISSUE TITLE
There are many Warning shows under the app.

### ISSUE THREAD

**Issue by wind13** [vikeri/re-navigate#4]
The warning is like this:

Warning: You are manually calling a React.PropTypes validation function for the 'borderBottomLeftRadius' prop on 'RCTImageView'.

This is deprecated and will not work in the next major version.

You may be seeing this warning due to a third-party PropTypes library.

See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by vikeri** [comment]
Just merged a PR for RN 0.31.0, can you test it with that and see if the error persists? If not, please specify Android/iOS

**Comment by wind13** [comment]
Thanks, test it and works fine. I was tested in Android. But it runs looks very slow, I don't know why?

Is it because the demo or debug version?

**Comment by vikeri** [comment]
Not sure about the performance thing, have only worked in iOS so far and not gotten into optimizing the performance of that app either. (Don't want to _prematurely optimize_). So I don't know. Needs further investigation. I'll close this issue now though since it was related to in app warnings. Feel free to open a new one about performance if you want.
